import 'dart:math';

final List<String> fortunes = [
  "Good fortune awaits in the near future.",
  "Don't rush into important matters.",
  "Be attentive to details.",
  "Good news is expected soon.",
  "Great inspiration is expected.",
  "Be careful what you say.",
  "Do not jump to conclusions.",
  "It is important to have patience.",
  "The fate is favorable to you.",
  "You will gain valuable experience.",
  "Your work will be fruitful.",
  "Your mistakes will make you stronger.",
  "Lose friends if you start looking for flaws in them.",
  "Ignore possible provocations.",
  "Problems at work will eventually turn into success.",
  "Don't try to do two things at the same time.",
  "There will be a difficult choice.",
  "Fate will give you a second chance.",
  "You will need help to catch your luck.",
  "A stranger will help you in business.",
  "Happiness is already standing outside your door.",
  "Pay close attention to your health.",
  "Your intuition will not let you down this year.",
  "Very soon you will meet an interesting person.",
  "Your future love is waiting for its time.",
  "You will be lucky in money matters.",
  "You will cry a lot, but only from joy.",
  "An interesting trip awaits you.",
  "Good luck will follow you in any endeavor.",
  "The year will bring peace and tranquility.",
  "All the year will help people who are now around.",
  "Cardinal changes are expected.",
  "Get ready for a romantic date.",
  "Rapid career growth awaits this year.",
  "Any business started will be successful.",
  "Expect real support from family.",
  "Need to take a rest! It's time to choose a new hobby.",
  "Devote more time to yourself.",
  "Meet a new love this year.",
  "A big acquisition in the near future.",
  "Everything you have planned will come true.",
  "The whole year will be filled with love and affection.",
  "The coming year will bring a lot of entertainment.",
  "You will find a new interesting occupation.",
  "It is time to show leadership qualities.",
  "Will win the lottery this year.",
  "Many interesting adventures await.",
  "Don't be afraid to do what you think is right.",
  "There is a high probability of a serious find.",
  "A favorable year for self-realization.",
  "Your efforts will pay off a hundredfold by the end of the week.",
  "You are likely to make good purchases and deals.",
  "You will achieve a lot if you take matters into your own hands.",
  "You know what you need and how to achieve it.",
  "Tomorrow new and exciting opportunities will open up for you.",
  "Your long-held dream will come true.",
  "A new journey will fill your life with unforgettable memories.",
  "A stranger will soon enter your life to share his happiness with you.",
  "Exciting events await you in the near future.",
  "Accept your past without regrets.",
  "Deal with the present with confidence.",
  "Face the future without fear.",
  "Taking action on time will help you confront your destiny.",
  "One person is seeking the way to your heart.",
  "Everyone agrees that you are the best.",
  "Fortune favors the brave.",
  "A loyal friend will stand in your defense.",
  "A new beginning awaits you.",
  "Remember that a true friend needs your time, not your money.",
  "In the near future you will have to risk something.",
  "A gambler will lose not only what he has, but also what he doesn't have.",
  "A golden opportunity will descend on you this month.",
  "It's a good time to finalize old business.",
  "Your intuition is trying to tell you something.",
  "You will soon meet a person who will become your friend for life.",
  "There is boundless happiness ahead of you.",
  "A light heart will help you get through all difficult times.",
  "A pleasant surprise awaits you.",
  "Your smile will open many doors for you.",
  "A long journey awaits you that will fulfill your expectations.",
  "Do what you love. The rest will fall into place.",
  "An adventure can bring you real happiness.",
  "Your advice will be of great help to a loved one.",
  "All the efforts you put in will eventually pay off.",
  "All the problems you have now will pass very quickly.",
  "You will do well with a new project.",
  "All your hard work will soon bear fruit.",
  "Let your intuition guide your decisions.",
  "An acquaintance from the past will influence you in the near future.",
  "You may have a pleasant romance soon.",
  "An important person will offer you support.",
  "Any decision you make tomorrow will be a good decision.",
  "Be careful, or you may become a victim of deception.",
  "Believe in yourself, and those around you will believe in you.",
  "Believe that anything is possible.",
  "It is better to ask twice than to lose once.",
  "Take your time, success is near.",
  "Do not stray from the path that is destined for you by fate.",
  "Do not take on extra work.",
  "The person you care about is looking for reconciliation.",
];

String getRandomFortune() {
  final random = Random();
  int index = random.nextInt(fortunes.length);
  return fortunes[index];
}
